// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dbsql

import (
	"database/sql"
)

type Associado struct {
	Codigo             string
	Nome               sql.NullString
	Endereco           sql.NullString
	Numero             sql.NullString
	Nascimento         sql.NullTime
	Salario            sql.NullFloat64
	Limite             sql.NullFloat64
	Empregador         int32
	Cep                sql.NullString
	Telres             sql.NullString
	Telcom             sql.NullString
	Cel                sql.NullString
	Bairro             sql.NullString
	ID                 int64
	Complemento        sql.NullString
	Cidade             sql.NullString
	Foto               []byte
	Rg                 sql.NullString
	Cpf                sql.NullString
	Funcao             sql.NullInt32
	Filiado            sql.NullBool
	Obs                sql.NullString
	IDSituacao         sql.NullInt32
	DataFiliacao       sql.NullTime
	DataDesfiliacao    sql.NullTime
	Email              sql.NullString
	Tipo               sql.NullInt32
	CodigoIsa          sql.NullString
	ParcelasPermitidas sql.NullInt32
	Uf                 sql.NullString
	Celwatzap          sql.NullBool
	TokenAssociado     sql.NullString
	CartaoEntregue     sql.NullBool
	DataEntregCartao   sql.NullTime
	UltimoMes          sql.NullString
	IDDivisao          sql.NullInt32
	IDSecretaria       sql.NullInt32
	Localizacao        sql.NullString
}

type Divisao struct {
	Nome      string
	Cidade    string
	IDDivisao int64
	Descricao sql.NullString
}

type Empregador struct {
	ID          int64
	Nome        sql.NullString
	Responsavel sql.NullString
	Telefone    sql.NullString
	Abreviacao  sql.NullString
	Divisao     sql.NullInt32
}

type Secretaria struct {
	IDSecretaria   int64
	NomeSecretaria sql.NullString
	Descri         sql.NullString
}

type SituacaoAssociado struct {
	Codigo int64
	Nome   sql.NullString
}

type TipoAssociado struct {
	IDTipoAssociado int64
	Nome            sql.NullString
}
